name: List PR Commits

on:
  pull_request:
    branches:
      - main

jobs:
  list-pr-commits:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub Pull Request Context
        id: github_context_step
        run: echo '${{ toJSON(github.event.pullrequest) }}'